spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpabulletin
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # data definition language / create옵션은 어플실행시점에 테이블 drop하고 다시생성
    properties:
      hibernate:
#        show_sql: true       #system.out에 하이버네이트 실행 SQL을 남긴다
        format_sql: true      #sql문을 줄 띄워서 예쁘게 보고싶을때

logging.level:
  org.hibernate.SQL: debug    #logger를 통해 하이버네이트 실행 SQL을 남긴다
  org.hibernate.type: trace
